### PR TITLE
Doc site as frames

### PR DESCRIPTION
**Pull request by compmstr**
With this set up, the docs are using frames
It's set up so that you can still bookmark individual pages
  Each of the sidebar links sets a hash at the end of the url that lets the main index page load the proper frame
At the top of each content frame, there's a 'Frames' link that will take you to the same page, but within the frames
  This is for people who open the sidebar links in another tab, so they can get back to the main content.

### CODE REVIEW

**Comment by oakes** [comment]
Sorry for taking so long to check this out. Looks like an interesting solution to #45. The downside is that existing links will be broken, and the new links will now depend on JavaScript (I use NoScript sometimes). Not sure if that is worth the upside of fixing the scroll position problem, since that can be solved by opening doc pages in separate tabs.

**Comment by compmstr** [comment]
The bookmarks should still work, it will take them to the content-only page, where they can click the 'Frames' link to go back to the page with the menu.
Hmm, the main thing that wouldn't work with noscript is the main index page auto-loading content for you.  The menu would still work fine.

**Comment by compmstr** [comment]
Sorry, the existing links should still work, all of the same pages are generated, just as content-only pages.

**Comment by oakes** [comment]
I made a few touch-ups and now I'm happy with it. Instead of a separate "Frames" link, I just linkified the header. I also improved the sidebar scroller. Thanks for your work.

**Pull request merged**
