### PR TITLE
set input processor on Stage only once, in :show.

### PR DESCRIPTION
**Pull request by floybix**
This seems to fix the ui button non-responsiveness issue I noted in #75.

Maybe it was some concurrent modification thing on the inputMultiplexer.

### CODE REVIEW

**Comment by oakes** [comment]
Please try the latest commit. It attempts to fix the issue by checking if the screen exists already in the input multiplexer. Your version looked fine but I wanted to minimize the changes to prevent unintentional breakages.

**Comment by floybix** [comment]
OK, that seems to work as well as my patch.  I do still see unresponsiveness sometimes -- if I add the actors to the stage later rather than creating them in the show function perhaps but haven't narrowed it down properly...

**Comment by floybix** [comment]
I just noticed that, while this commit fixed the ui actors which is great, it did something to on-touch-down.  Specifically (at least in my game) it now only fires in the outermost 1 or 2 pixels around the stage. Which suggests that it may be masked by the ui touch down listener - though i haven't looked into it.

**Comment by oakes** [comment]
Does this problem exist in your change?

**Comment by floybix** [comment]
Actually, no. But I don't know why.

**Comment by oakes** [comment]
On second thought, your version seems pretty safe, and doesn't do any unnecessary removals of actors. So, I'll use it instead.

**Pull request merged**
